In [1]:
import numpy as np

In [2]:
data=np.loadtxt('glass.csv',delimiter=',') #Loading the data Set

In [14]:
data

array([[  1.     ,   1.52101,  13.64   , ...,   0.     ,   0.     ,
          1.     ],
       [  2.     ,   1.51761,  13.89   , ...,   0.     ,   0.     ,
          1.     ],
       [  3.     ,   1.51618,  13.53   , ...,   0.     ,   0.     ,
          1.     ],
       ...,
       [212.     ,   1.52065,  14.36   , ...,   1.64   ,   0.     ,
          7.     ],
       [213.     ,   1.51651,  14.38   , ...,   1.57   ,   0.     ,
          7.     ],
       [214.     ,   1.51711,  14.23   , ...,   1.67   ,   0.     ,
          7.     ]])

In [8]:
print(data.ndim) #Find the Number of dimensions 
print(data.shape) #Find the shape of data

2
(214, 11)


In [9]:
# Get type
print(type(data))
data.dtype

<class 'numpy.ndarray'>


dtype('float64')

In [18]:
#First colunm
data[:,0]

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 15

In [23]:
#Remove First colunm
data[:,1:]

array([[ 1.52101, 13.64   ,  4.49   , ...,  0.     ,  0.     ,  1.     ],
       [ 1.51761, 13.89   ,  3.6    , ...,  0.     ,  0.     ,  1.     ],
       [ 1.51618, 13.53   ,  3.55   , ...,  0.     ,  0.     ,  1.     ],
       ...,
       [ 1.52065, 14.36   ,  0.     , ...,  1.64   ,  0.     ,  7.     ],
       [ 1.51651, 14.38   ,  0.     , ...,  1.57   ,  0.     ,  7.     ],
       [ 1.51711, 14.23   ,  0.     , ...,  1.67   ,  0.     ,  7.     ]])

In [24]:
#Changes in the data set
update_Data=data[:,1:]
update_Data

array([[ 1.52101, 13.64   ,  4.49   , ...,  0.     ,  0.     ,  1.     ],
       [ 1.51761, 13.89   ,  3.6    , ...,  0.     ,  0.     ,  1.     ],
       [ 1.51618, 13.53   ,  3.55   , ...,  0.     ,  0.     ,  1.     ],
       ...,
       [ 1.52065, 14.36   ,  0.     , ...,  1.64   ,  0.     ,  7.     ],
       [ 1.51651, 14.38   ,  0.     , ...,  1.57   ,  0.     ,  7.     ],
       [ 1.51711, 14.23   ,  0.     , ...,  1.67   ,  0.     ,  7.     ]])

In [31]:
# Get the maximum values of the whole data set
max_In_data = np.amax(update_Data)
max_In_data

75.41

In [41]:
# Get the maximum values of each column i.e. along axis 0
maxInColumns = np.amax(update_Data, axis=0)
print('Max value of every column: ', maxInColumns)

Max value of every column:  [ 1.53393 17.38     4.49     3.5     75.41     6.21    16.19     3.15
  0.51     7.     ]


In [34]:
# Get the maximum values of each row i.e. along axis 1
maxInRows = np.amax(update_Data, axis=1)
print('Max value of every Row: ', maxInRows)

Max value of every Row:  [71.78 72.73 72.99 72.61 73.08 72.97 73.09 73.24 72.08 72.99 73.2  73.01
 73.28 73.21 73.29 73.24 73.11 71.36 72.12 72.73 72.75 72.02 72.79 73.02
 72.85 73.   72.64 73.04 73.15 72.86 73.08 73.27 72.97 73.39 72.95 72.74
 71.81 72.96 71.77 71.77 73.03 73.2  72.76 71.76 72.95 71.95 72.72 71.57
 71.99 72.08 71.75 72.36 72.84 72.85 72.98 73.7  72.98 72.95 72.99 72.79
 72.64 71.72 71.79 71.35 72.01 71.96 72.22 72.32 72.2  71.99 71.87 71.96
 73.1  72.87 73.11 73.12 72.39 72.83 72.88 72.86 72.66 73.17 72.81 72.87
 72.28 72.72 73.25 72.65 72.89 73.23 72.28 73.06 73.26 73.1  73.28 72.26
 72.34 73.55 73.21 72.92 73.27 72.87 73.81 70.57 71.15 72.19 69.81 70.16
 72.67 74.45 73.21 73.08 72.02 72.55 72.44 72.38 72.33 72.06 72.53 72.45
 72.4  72.96 72.84 72.52 72.75 72.51 72.75 71.99 72.18 71.76 72.19 71.24
 72.49 71.81 72.78 72.33 73.07 72.96 73.36 73.14 72.54 72.83 73.01 72.72
 72.97 72.57 72.77 72.67 72.7  72.89 72.48 71.5  73.   72.69 72.61 73.01
 72.64 71.79 72.04 71.94 7

In [43]:
# Get the maximum values in row
maxIn_first_Rows = np.amax(update_Data[0,:])
maxIn_first_Rows
update_Data[0,:]

array([1.52101e+00, 1.36400e+01, 4.49000e+00, 1.10000e+00, 7.17800e+01,
       6.00000e-02, 8.75000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00])

In [45]:
# Get the maximum values first in row
maxIn_first_Rows = np.amax(update_Data[0,:])
maxIn_first_Rows

71.78

In [49]:
# Get the maximum values first in colunm
maxIn_first_colunm = np.amax(update_Data[:,0])
maxIn_first_colunm

1.53393

In [50]:
#Same for the minimum np.amin()

In [51]:
# Get the mean values of each column i.e. along axis 0
np.mean(update_Data, axis=0)

array([1.51836542e+00, 1.34078505e+01, 2.68453271e+00, 1.44490654e+00,
       7.26509346e+01, 4.97056075e-01, 8.95696262e+00, 1.75046729e-01,
       5.70093458e-02, 2.78037383e+00])

In [52]:
# Get the mean values of each column i.e. along axis 0
np.mean(update_Data, axis=1)

array([10.234101, 10.240761, 10.229618, 10.210766, 10.234742, 10.247596,
       10.239743, 10.237756, 10.244918, 10.254755, 10.245571, 10.241763,
       10.248589, 10.250748, 10.239763, 10.230761, 10.244784, 10.228196,
       10.239911, 10.254735, 10.23775 , 10.237966, 10.228736, 10.247751,
       10.23272 , 10.242764, 10.227793, 10.222721, 10.228768, 10.231784,
       10.254768, 10.237747, 10.252775, 10.253753, 10.235783, 10.233567,
       10.246909, 10.236797, 10.247213, 10.247213, 10.236793, 10.227755,
       10.238779, 10.24821 , 10.249786, 10.2339  , 10.253869, 10.243667,
       10.243223, 10.225898, 10.25332 , 10.253926, 10.242808, 10.224837,
       10.242778, 10.252769, 10.235215, 10.213824, 10.251754, 10.249754,
       10.238905, 10.242977, 10.244172, 10.232227, 10.251172, 10.237099,
       10.252152, 10.262152, 10.253152, 10.2543  , 10.329574, 10.343848,
       10.331593, 10.336631, 10.336596, 10.33959 , 10.318645, 10.311627,
       10.353613, 10.32759 , 10.333592, 10.328593, 

In [61]:
update_Data

array([[ 1.52101, 13.64   ,  4.49   , ...,  0.     ,  0.     ,  1.     ],
       [ 1.51761, 13.89   ,  3.6    , ...,  0.     ,  0.     ,  1.     ],
       [ 1.51618, 13.53   ,  3.55   , ...,  0.     ,  0.     ,  1.     ],
       ...,
       [ 1.52065, 14.36   ,  0.     , ...,  1.64   ,  0.     ,  7.     ],
       [ 1.51651, 14.38   ,  0.     , ...,  1.57   ,  0.     ,  7.     ],
       [ 1.51711, 14.23   ,  0.     , ...,  1.67   ,  0.     ,  7.     ]])

In [62]:
np.amax(update_Data)

75.41

In [67]:
#Most Important Point
# Rescale the values b/w 0 to 1
Rescale_dataSet=update_Data/np.amax(update_Data)
Rescale_dataSet

array([[0.02016987, 0.18087787, 0.05954117, ..., 0.        , 0.        ,
        0.01326084],
       [0.02012478, 0.18419308, 0.04773903, ..., 0.        , 0.        ,
        0.01326084],
       [0.02010582, 0.17941918, 0.04707598, ..., 0.        , 0.        ,
        0.01326084],
       ...,
       [0.0201651 , 0.19042567, 0.        , ..., 0.02174778, 0.        ,
        0.09282589],
       [0.0201102 , 0.19069089, 0.        , ..., 0.02081952, 0.        ,
        0.09282589],
       [0.02011815, 0.18870176, 0.        , ..., 0.0221456 , 0.        ,
        0.09282589]])

In [68]:
np.amax(Rescale_dataSet)

1.0

In [69]:
#Reshape
update_Data.shape

(214, 10)

In [70]:
Transpose_data=update_Data.reshape(10,214)

In [71]:
Transpose_data.shape

(10, 214)

In [72]:
# Task Convert dic into numpy array

In [6]:
dict={1:'ML',2:'DL',3:'CV',4:'NLP'}

In [13]:
  
# to return a group of value
result = dict.values()
  
# Convert object to a list
data = list(result)
data

['ML', 'DL', 'CV', 'NLP']

In [15]:
# Convert list to an array
numpyArray = np.array(data)
  
# print the numpy array
print(numpyArray)

['ML' 'DL' 'CV' 'NLP']


numpy.ndarray